# Generated by Django 3.2.16 on 2022-11-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_category_products_catagory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'ordering': ('name',), 'verbose_name': 'catagory', 'verbose_name_plural': 'catagories'},
        ),
        migrations.AlterField(
            model_name='catagory',
            name='image',
            field=models.ImageField(blank=True, upload_to='catagory'),
        ),
    ]
